services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@db:5432/todo_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always    # <--- This forces Docker to restart the backend if it crashes on startup

  frontend:
    build: ./frontend
    ports:
      - "5500:80"
    depends_on:
      - backend

volumes:
  postgres_data: